'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const pieces=[['Manteau long, laine vierge','Manteau, laine vierge'],['Robe fluide, soie','Robe, soie'],['Ensemble tailleur, gabardine','Ensemble, gabardine'],['Veste ample, cachemire','Veste, cachemire'],['Blouse, soie','Blouse, soie'],['Jupe structurée, cuir','Jupe, cuir'],['Cape drapée, laine','Cape, laine'],['Robe du soir, soie','Robe du soir, soie']];
const disclaimer='Concept créé par Megahana — marque fictive à des fins de démonstration.';
export default function Home(){const [menu,setMenu]=useState(false),[appointment,setAppointment]=useState(false),[nav,setNav]=useState(false);const root=useRef<HTMLDivElement>(null),dot=useRef<HTMLDivElement>(null);
useEffect(()=>{const observer=new IntersectionObserver(([e])=>setNav(!e.isIntersecting),{threshold:.15});const hero=root.current?.querySelector('.hero');if(hero)observer.observe(hero);let dead=false,destroy=()=>{};
if(!matchMedia('(prefers-reduced-motion: reduce)').matches)Promise.all([import('gsap'),import('gsap/ScrollTrigger')]).then(([{gsap},{ScrollTrigger}])=>{if(dead)return;gsap.registerPlugin(ScrollTrigger);const ctx=gsap.context(()=>{gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.fromTo(el,{opacity:0,y:20},{opacity:1,y:0,duration:1.6,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 95%',once:true}}));gsap.utils.toArray<HTMLElement>('.piece-photo').forEach(el=>gsap.fromTo(el,{scale:1.035},{scale:1,ease:'none',scrollTrigger:{trigger:el.closest('article'),start:'top bottom',end:'bottom top',scrub:1.8}}))},root);destroy=()=>ctx.revert()}).catch(()=>{});
let frame=0,x=0,y=0;const move=(e:PointerEvent)=>{x=e.clientX;y=e.clientY;if(!frame)frame=requestAnimationFrame(()=>{frame=0;if(dot.current){dot.current.style.transform=`translate3d(${x}px,${y}px,0)`;dot.current.style.opacity='1'}});dot.current?.classList.toggle('large',!!(e.target as Element).closest('a,button'))};const fine=matchMedia('(hover:hover) and (pointer:fine)').matches;if(fine)window.addEventListener('pointermove',move,{passive:true});return()=>{dead=true;observer.disconnect();destroy();cancelAnimationFrame(frame);window.removeEventListener('pointermove',move)}},[]);
return <div ref={root}><div className="cursor" ref={dot} aria-hidden="true"/><header className={nav?'visible':''} inert={!nav}><button className="wordmark" aria-label="Ouvrir le menu" onClick={()=>setMenu(true)}>Elyra</button></header><main>
<section className="hero"><img src="/photos/01.webp" alt="" fetchPriority="high" width="1100" height="1650"/><h1>Elyra</h1></section>
<section id="maison" className="house"><div className="editorial reveal"><h2>Maison Elyra</h2><p>Elyra présente une collection par saison, en série volontairement limitée. Chaque pièce est visible sur rendez-vous, avant d'être proposée en ligne. La maison ne communique pas de prix publiquement — l'accès se fait sur demande.</p></div><figure className="campaign reveal"><img src="/photos/09.webp" alt="Campagne Maison Elyra" width="1600" height="900" loading="lazy"/></figure></section>
<section id="collection" className="collection" aria-label="La collection">{pieces.map(([label],i)=><article className="piece" id={`piece-${i+1}`} key={label}><figure tabIndex={0} className="piece-frame"><img className="piece-photo" src={`/photos/${String(i+1).padStart(2,'0')}.webp`} alt={label} width="1100" height="1650" loading="lazy"/><figcaption><span>{String(i+1).padStart(2,'0')}</span><span>{label}</span></figcaption></figure></article>)}</section>
<section id="savoir-faire" className="craft"><div className="editorial reveal"><h2>Fabriqué en France</h2><p>Les pièces Elyra sont façonnées dans un atelier partenaire en région parisienne. Chaque vêtement passe par plusieurs mains avant d'être terminé — coupe, montage, finitions à la main.</p></div><div className="details"><figure className="reveal"><img src="/photos/10.webp" alt="Couture et laine" width="1200" height="900" loading="lazy"/></figure><figure className="reveal"><img src="/photos/11.webp" alt="Finitions à la main" width="1200" height="900" loading="lazy"/></figure></div></section>
<section id="index" className="index"><h2 className="reveal">Index</h2><ol>{pieces.map(([,label],i)=><li key={label}><a href={`#piece-${i+1}`}>{String(i+1).padStart(2,'0')} — {label}</a></li>)}</ol></section>
<section id="rendez-vous" className="appointment"><div className="reveal"><h2>Prendre rendez-vous</h2><p>La collection se découvre sur rendez-vous, à l'atelier ou en ligne.</p><button className="appointment-link" onClick={()=>setAppointment(true)}>Demander un rendez-vous</button></div></section>
</main><footer>{disclaimer}</footer><Dialog open={menu} onOpenChange={setMenu}><DialogContent className="menu-dialog" aria-describedby={undefined}><DialogTitle className="sr-only">Elyra</DialogTitle><nav aria-label="Navigation principale">{[['maison','Maison Elyra'],['collection','La collection'],['savoir-faire','Fabriqué en France'],['index','Index'],['rendez-vous','Prendre rendez-vous']].map(([id,label])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}</nav></DialogContent></Dialog><Dialog open={appointment} onOpenChange={setAppointment}><DialogContent className="appointment-dialog"><DialogTitle>Prendre rendez-vous</DialogTitle><DialogDescription>La collection se découvre sur rendez-vous, à l'atelier ou en ligne.</DialogDescription><p className="disclaimer">{disclaimer}</p></DialogContent></Dialog></div>}
